# Generated by Django 4.2.5 on 2023-09-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Image', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=20)),
                ('Info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=20)),
                ('Mail', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Nickname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('Reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('Creation_date', models.DateField()),
                ('Formation_date', models.DateField()),
                ('Completion_date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reservations', to='bmstu.users')),
                ('Moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_reservations', to='bmstu.users')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_info', models.CharField(max_length=20)),
                ('Group_size', models.IntegerField()),
                ('Date', models.DateField()),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu.events')),
                ('Reserve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu.reservations')),
            ],
        ),
    ]
