# Generated by Django 4.2.5 on 2023-09-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_reservation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
