# Generated by Django 4.2.4 on 2023-12-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Image', models.ImageField(upload_to='events/')),
                ('Status', models.CharField(choices=[('A', 'Доступно'), ('C', 'Завершено'), ('S', 'Скоро'), ('D', 'Удалено')], max_length=20)),
                ('Info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bmstu_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bmstu_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('Reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('Creation_date', models.DateTimeField()),
                ('Formation_date', models.DateTimeField(null=True)),
                ('Completion_date', models.DateTimeField(null=True)),
                ('Status', models.CharField(choices=[('M', 'Черновик'), ('iP', 'В работе'), ('C', 'Завершена'), ('Ca', 'Отменена'), ('D', 'Удалена')], max_length=20)),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reservations', to='stocks.users')),
                ('Moderator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_reservations', to='stocks.users')),
            ],
            options={
                'db_table': 'bmstu_reservations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_info', models.CharField(max_length=20)),
                ('Group_size', models.IntegerField()),
                ('Date', models.DateField()),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.events')),
                ('Reserve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.reservations')),
            ],
            options={
                'db_table': 'bmstu_event_reservation',
                'managed': True,
            },
        ),
    ]
