# Generated by Django 4.2.4 on 2023-10-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_info', models.CharField(max_length=20)),
                ('Group_size', models.IntegerField()),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'bmstu_event_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Image', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('A', 'Доступно'), ('C', 'Завершено'), ('S', 'Скоро'), ('D', 'Удалено')], max_length=20)),
                ('Info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bmstu_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('Reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('Creation_date', models.DateTimeField()),
                ('Formation_date', models.DateTimeField()),
                ('Completion_date', models.DateTimeField()),
                ('Status', models.CharField(choices=[('M', 'Made'), ('iP', 'In Progress'), ('C', 'Completed'), ('Ca', 'Canceled'), ('D', 'Deleted')], max_length=2)),
            ],
            options={
                'db_table': 'bmstu_reservations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=20)),
                ('Mail', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Nickname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bmstu_users',
                'managed': False,
            },
        ),
    ]
