# Generated by Django 4.2.4 on 2023-12-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='Available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
