# Generated by Django 4.2.4 on 2023-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_reservations_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
